name: CI + Security Scans + CodeQL

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 3 * * 1'  # Weekly Monday run for CodeQL

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  build-test-sec:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install sarif-tools


      # 4. Run pytest (basic unit test)
      - name: Run pytest
        run: pytest -q

      # 5. Bandit SAST -> JSON -> SARIF
      - name: Run Bandit (output JSON)
        run: |
          bandit -r . \
            --severity-level medium \
            --confidence-level medium \
            -f json -o bandit.json

      - name: Convert Bandit JSON to SARIF
        run: python -m sarif_tools from-bandit bandit.json bandit.sarif

      - name: Upload Bandit SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bandit.sarif

      # 6. pip-audit dependency scan
      - name: pip-audit
        run: |
          pip-audit -r requirements.txt -f json -o pip-audit.json
          python -m sarif_tools from-pip-audit pip-audit.json pip-audit.sarif

      - name: Upload pip-audit SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pip-audit.sarif

      # 7. Gitleaks secrets scan
      - name: Gitleaks – secrets detection
        uses: zricethezav/gitleaks-action@v2
        with:
          args: detect --no-git -v --redact --report-format json --report-path gitleaks.json

      - name: Convert Gitleaks JSON to SARIF
        run: python -m sarif_tools from-gitleaks gitleaks.json gitleaks.sarif

      - name: Upload Gitleaks SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif

      # 8. Save all raw reports as artifacts
      - name: Upload raw reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            *.json
            *.sarif

  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: '/language:${{matrix.language}}'
